name: github pages

# mainブランチにプッシュしたときjobsに記述した操作を行う
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    # ubuntu OS を仮想マシン上に用意する
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

      # Node.js環境のセットアップを行う
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      # package.jsonに基づき依存パッケージをインストールする
      - name: install
        run: npm install --frozen-lockfile

      # Next.jsアプリをビルドする
      - name: build
        run: npm run build

      # gh-pagesブランチにoutディレクトリの中身をプッシュする
      # gh-pagesブランチは自動的に作成される
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
